[package]
name = "laid_dot"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axgeom="1.2.1"
ascii_num={path="../ascii_num"}